# Generated by Django 3.2.7 on 2021-11-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_donation', models.FloatField()),
                ('gift_registry_donation', models.FloatField()),
                ('total_donation', models.FloatField()),
                ('invited', models.BooleanField()),
                ('donation_date', models.CharField(default='2021-11-23 / 15:40:58', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaign.campaign')),
            ],
        ),
    ]
