# Generated by Django 3.2.7 on 2021-11-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_description', models.CharField(max_length=255)),
                ('creation_date', models.CharField(default='2021-11-23 / 15:40:58', max_length=50)),
                ('campaign_objetive', models.IntegerField()),
                ('ubication', models.CharField(max_length=100)),
                ('url_campaign', models.CharField(max_length=50, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'pendiente'), (2, 'aceptada'), (3, 'finalizada')])),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='media')),
                ('is_portada', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='campaign.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='campaign.campaigncategory'),
        ),
    ]
